$ ./100-run-experiment.sh
[INFO] Cleaning veths
[INFO] Creating docker containers
[INFO] Setting up pipework
[INFO] Starting ZooKeeper
[INFO] Waiting for 5 seconds
[INFO] Stopping inspection
[INFO] Checking whether the bug was reproduced
Parsing Zookeeper version: 3.6.0-SNAPSHOT--1, built on 06/09/2015 11:53 GMT
Clients:
 /192.168.42.254:54882[0](queued=0,recved=1,sent=0)

Latency min/avg/max: 0/0/0
Received: 1
Sent: 0
Connections: 1
Outstanding: 0
Zxid: 0x100000000
Mode: leader
Node count: 5
:
Parsed {'zxid': '0x100000000', 'mode': 'leader'}:
Parsing Zookeeper version: 3.6.0-SNAPSHOT--1, built on 06/09/2015 11:53 GMT
Clients:
 /192.168.42.254:59740[0](queued=0,recved=1,sent=0)

Latency min/avg/max: 0/0/0
Received: 1
Sent: 0
Connections: 1
Outstanding: 0
Zxid: 0x100000000
Mode: observer
Node count: 5
:
Parsed {'zxid': '0x100000000', 'mode': 'observer'}:
Parsing Zookeeper version: 3.6.0-SNAPSHOT--1, built on 06/09/2015 11:53 GMT
Clients:
 /192.168.42.254:39963[0](queued=0,recved=1,sent=0)

Latency min/avg/max: 0/0/0
Received: 1
Sent: 0
Connections: 1
Outstanding: 0
Zxid: 0x100000000
Mode: observer
Node count: 5
:
Parsed {'zxid': '0x100000000', 'mode': 'observer'}:
Traceback (most recent call last):
  File "./check.py", line 47, in <module>
    main()
  File "./check.py", line 43, in main
    assert len(observers) == 0, 'Bad observers: %s' % l
AssertionError: Bad observers: [{'zxid': '0x100000000', 'mode': 'leader'}, {'zxid': '0x100000000', 'mode': 'observer'}, {'zxid': '0x100000000', 'mode': 'observer'}]
[IMPORTANT] THE BUG WAS REPRODUCED!
